# Generated by Django 4.1.5 on 2024-02-25 09:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auto_interview', '0002_userprofile_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='dataProfile',
        ),
    ]
